name: Metrics
on:
  # Updated daily
  schedule: [{cron: "0 0 * * *"}]
  # Or manually
  workflow_dispatch:
  # Or when pushing to main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
